parameters:
    nyroDev_utility.queryBuilder.class: NyroDev\UtilityBundle\QueryBuilder\OrmQueryBuilder
    
services:
    NyroDev\UtilityBundle\Services\Db\DbAbstractService:
        alias: NyroDev\UtilityBundle\Services\Db\OrmService
        public: true

    NyroDev\UtilityBundle\Services\Db\OrmService:
        arguments: ['@service_container', '@nyrodev.entity_manager']
        public: true
    nyrodev_db:
        alias: NyroDev\UtilityBundle\Services\Db\OrmService
        public: true

    nyrodev.entity_manager:
        class: Doctrine\ORM\EntityManager
        arguments: ["%nyroDev_utility.model_manager_name%"]
        public: true
