parameters:
    nyroDev_utility.admin.nbPerPage: 25

services:
    NyroDev\UtilityBundle\Services\MainService:
        alias: nyrodev
        arguments: ['@service_container']
        public: true
        tags:
          - { name: templating.helper, alias: nyrodev }
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: -10 }
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }

    NyroDev\UtilityBundle\Services\TagRendererService:
        alias: nyrodev_tagRender
        arguments: ['@service_container', '@webpack_encore.entrypoint_lookup_collection', '@assets.packages']
        public: true
        tags:
          - { name: templating.helper, alias: nyrodev_tagRender }

    NyroDev\UtilityBundle\Services\ShareService:
        alias: nyrodev_share:
        arguments: ['@service_container']
        public: true
        tags:
          - { name: templating.helper, alias: nyrodev_share }

    NyroDev\UtilityBundle\Services\MemberService:
        alias: nyrodev_member:
        arguments: ['@service_container']
        public: true
        tags:
          - { name: templating.helper, alias: nyrodev_member }

    NyroDev\UtilityBundle\Services\ImageService:
        alias: nyrodev_image:
        arguments: ['@service_container', '@templating.helper.assets']
        public: true
        tags:
          - { name: templating.helper, alias: nyrodev_image }

    NyroDev\UtilityBundle\Services\FormService:
        alias: nyrodev_form:
        arguments: ['@service_container', '@templating.helper.assets']
        public: true
        tags:
          - { name: templating.helper, alias: nyrodev_form }

    NyroDev\UtilityBundle\Services\FormFilterService:
        alias: nyrodev_formFilter:
        arguments: ['@service_container']
        public: true

    NyroDev\UtilityBundle\Services\EmbedService:
        alias: nyrodev_embed:
        arguments: ['@service_container']
        public: true
        tags:
          - { name: templating.helper, alias: nyrodev_embed }
    
    NyroDev\UtilityBundle\Services\EmbedValidatorService:
        alias: nyrodev_embed_validator:
        arguments: ['@service_container']
        public: true
        tags:
          - { name: validator.constraint_validator, alias: nyrodev_embed_validator }
