parameters:
    nyrodev_utility.ormDbService.class: NyroDev\UtilityBundle\Services\Db\OrmService
    nyrodev_utility.ormQueryBuilder.class: NyroDev\UtilityBundle\QueryBuilder\OrmQueryBuilder
    
services:
    nyrodev_db:
        class: %nyrodev_utility.ormDbService.class%
        arguments: [@service_container, @nyrodev.entity_manager]
    nyrodev.entity_manager:
        class: Doctrine\ORM\EntityManager
        arguments: [%nyroDev_utility.model_manager_name%]
