parameters:
    nyrodev_utility.mongodbDbService.class: NyroDev\UtilityBundle\Services\Db\MongodbService
    nyrodev_utility.queryBuilder.class: NyroDev\UtilityBundle\QueryBuilder\MongodbQueryBuilder
    
services:
    nyrodev_db:
        class: %nyrodev_utility.mongodbDbService.class%
        arguments: ['@service_container', '@nyrodev.document_manager']
    nyrodev.document_manager:
        class: Doctrine\ODM\MongoDB\DocumentManager
        arguments: [%nyroDev_utility.model_manager_name%]
