parameters:
    nyrodev_utility.mainService.class: NyroDev\UtilityBundle\Services\MainService
    nyrodev_utility.shareService.class: NyroDev\UtilityBundle\Services\ShareService
    nyrodev_utility.memberService.class: NyroDev\UtilityBundle\Services\MemberService
    nyrodev_utility.imageService.class: NyroDev\UtilityBundle\Services\ImageService
    nyrodev_utility.formService.class: NyroDev\UtilityBundle\Services\FormService
    nyrodev_utility.formFilterService.class: NyroDev\UtilityBundle\Services\FormFilterService
    nyrodev_utility.embedService.class: NyroDev\UtilityBundle\Services\EmbedService
    nyrodev_utility.embedValidatorService.class: NyroDev\UtilityBundle\Services\EmbedValidatorService
    nyrodev_utility.admin.nbPerPage: 25

services:
    nyrodev:
        class: %nyrodev_utility.mainService.class%
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrodev }
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
          - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    nyrodev_share:
        class: %nyrodev_utility.shareService.class%
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrodev_share }
    nyrodev_member:
        class: %nyrodev_utility.memberService.class%
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrodev_member }
    nyrodev_image:
        class: %nyrodev_utility.imageService.class%
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrodev_image }
    nyrodev_form:
        class: %nyrodev_utility.formService.class%
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrodev_form }
    nyrodev_formFilter:
        class: %nyrodev_utility.formFilterService.class%
        arguments: ['@service_container']
    nyrodev_embed:
        class: %nyrodev_utility.embedService.class%
        arguments: ['@service_container']
        tags:
          - { name: templating.helper, alias: nyrodev_embed }
    nyrodev_embed_validator:
        class: %nyrodev_utility.embedValidatorService.class%
        arguments: ['@service_container']
        tags:
          - { name: validator.constraint_validator, alias: nyrodev_embed_validator }
